name: JS

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'src/**'
      - 'spec/ts/**'
      - 'spec/fixtures/**'
      - 'spec/generate.mjs'
      - 'tsconfig.json'
      - 'package.json'
      - 'yarn.lock'
      - 'eslint.config.cjs'
      - '.github/workflows/build-js.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: corepack enable
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn spec:ts
